name: Delete Preview Environment

on:
  pull_request:
    types: [closed]

env:
  REGION: cn-e1
  APP_ID: qEDh11pDkEjwJEemzrIMkYDc-9Nh9j0Va
  GROUP: web

jobs:
  delete-preview-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Install lean-cli
        run: |
          sudo curl -L -o /bin/lean http://releases.leanapp.cn/leancloud/lean-cli/releases/download/v1.1.0/lean-linux-x64
          sudo chmod +x /bin/lean

      - name: Delete
        run: |
          lean login --region ${{ env.REGION }} --token ${{ secrets.ACCESS_TOKEN }}
          lean switch --region ${{ env.REGION }} --group ${{ env.GROUP }} ${{ env.APP_ID }}
          lean preview delete

      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: preview/${{ github.head_ref }}
          onlyDeactivateDeployments: true
